### PR TITLE
General improvements

### LINKED ISSUE #177: Dropping C++11 for C++14
I noticed that the file writer is no longer being built with GCC 4.x by Jenkins. It is thus possible to move to C++14 by only switching a compiler flag.

Does anyone (@michele-brambilla @dominikwerder @matthew-d-jones ) have any objection to doing this?

### LINKED ISSUE #205: CLI documentation has wrong log level default
According to the CLI documentation obtained by invoking `kafka-to-nexus -h`, the default log level is 6 (Info), but it actually seems to be 3 — see line 17 of _logger.cpp_.

### LINKED ISSUE #210: Verify flatbuffer before first access
Make sure the `FlatbufferReader::verify()` is done before any access into the flatbuffer.

### PR DESCRIPTION
**Pull request by SkyToGround**
### Description of work

So this turned into a bit of a beast. It started out as a fix of issue #210 but it turned into something ... *more*.

The following should be a (mostly) complete list of what has been done.
* Fixes issue #210 by moving responsibility of getting flatbuffer metadata access into a new class: `FlatbufferMessage`.
* Removed duplicated functionality from a bunch of places, mostly `Streamer` and `DemuxTopic`.
* Added support for the trompeloeil mocking library in order to more easily implement unit tests.
* Changed over to using C++14 in order to be able to use trompeloeil.
* Removed a whole lot of dead code.
* Made some names more descriptive.
* Modified `KafkaW::Msg` to reduce coupling and thus simplify unit testing.
* Modified several classes to simplify future and current unit testing.
* Fixed several problems (i.e. bugs) found mostly in `Streamer`.

Because of the changes I made I had to touch a lot of files. I am sorry about and I will try to keep pull requests smaller in the future.

### Integration tests

I have so far done the following integration tests:

* Faulty kafka (flatbuffer) messages are ignored (manual test)
* Valid kafka (flatbuffer) messages with an unknown source name are ignored (manual test)
* Valid and  known kafka (flatbuffer) messages are written to file (manual test).
* Jenkins automatic integration test was [completed successfully.](https://jenkins.esss.dk/dm/job/ess-dmsc/job/integration-test/job/filewriter_test/)

There is one or two more integration tests will be done before I think we are ready to merge.

### Issue

* Closes #210 
* Closes #177 
* Closes #205 
* Relates to JIRA issue DM-398 and DM-399

### Acceptance Criteria

* Are there design problems with this implementation?
* Do we need more unit tests?
* How much documentation is the minimum required (currently I have added nothing).

### Unit Tests

* Added unit tests for `Streamer`, `DemuxTopic` and `FlatbufferMessage`.
* Modified or deleted (now useless unit tests) for several other classes/parts.

### Other

* There is still significant overlap in functionality between `Streamer` and `DemuxTopic`, I have deferred fixing that for now but maybe I should not. 

---

## Code Review (To be filled in by the reviewer only)

- [ ] Is the code of an acceptable quality?
- [ ] Do the changes function as described and is it robust?

---

## Nominate for Group Code Review (Anyone can nominate it)
Indicate if you think the code should be reviewed in a Thursday code review session.

- [x] Recommend for group code review

Also, nominate it on the code_review Slack channel (does someone want to automate this?).

### CODE REVIEW

File: src/FlatbufferMessage.cpp [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+    Valid = false;
+    throw UnknownFlatbufferID(fmt::format(
+        "Unable to locate reader with the ID \"{}\" in the registry.",
+        FlatbufferID));
+  }
+  Valid = true;
+}
+
+FlatbufferMessage::~FlatbufferMessage() {}
+}
```
Comment (mattclarke) [inline src/FlatbufferMessage.cpp]: = default

File: src/FlatbufferMessage.cpp [hunk 2]
```diff
@@ -0,0 +1,39 @@
+#include "FlatbufferMessage.h"
+#include "FlatbufferReader.h"
+
+namespace FileWriter {
+FlatbufferMessage::FlatbufferMessage() : Valid(false) {}
+
+FlatbufferMessage::FlatbufferMessage(char const *Pointer, size_t const Size)
+    : DataPtr(const_cast<char *>(Pointer)), DataSize(Size) {
```
Comment (mattclarke) [inline src/FlatbufferMessage.cpp]: Size being const has no effect?

File: src/FlatbufferReader.cpp [hunk 3]
```diff
@@ -13,23 +14,7 @@ std::map<std::string, FlatbufferReaderRegistry::ReaderPtr> &getReaders() {
...
-  static_assert(FLATBUFFERS_LITTLEENDIAN, "Requires currently little endian");
-  if (msg.size() < 8) {
-    LOG(Sev::Warning, "flatbuffer message is too small: {} expect at least 8",
-        msg.size());
-    static FlatbufferReader::ptr empty;
-    return empty;
-  }
-  std::string key(msg.data() + 4, 4);
-  return find(key);
+  return _items.at(key);
```
Comment (mattclarke) [inline src/FlatbufferReader.cpp]: empty no longer required?

File: src/Streamer.cpp [hunk 4]
```diff
@@ -43,102 +42,133 @@ FileWriter::Streamer::connect(std::string TopicName) {
...
   if (Options.StopTimestamp.count() > 0 &&
-      MessageTime.dt > std::chrono::duration_cast<std::chrono::nanoseconds>(
-                           Options.StopTimestamp)
-                           .count()) {
-    if (removeSource(MessageTime.sourcename)) {
-      return ProcessMessageResult::STOP();
+      static_cast<std::int64_t>(Message->getTimestamp()) >
+          std::chrono::duration_cast<std::chrono::nanoseconds>(
+              Options.StopTimestamp)
+              .count()) {
```
Comment (mattclarke) [inline src/Streamer.cpp]: bool stoptimeElapsed(std::uint64_t Timestamp, std::chrono::milliseconds Stoptime)

File: src/Source.cpp [hunk 5]
```diff
@@ -42,35 +42,30 @@ std::string const &Source::topic() const { return _topic; }
...
     if (ret.is_ERR()) {
-      return ProcessMessageResult::ERR();
+      return ProcessMessageResult::ERR;
     }
     if (HDFFileForSWMR) {
       HDFFileForSWMR->SWMRFlush();
     }
     if (ret.is_OK_WITH_TIMESTAMP()) {
-      return ProcessMessageResult::OK(ret.timestamp());
+      return ProcessMessageResult::OK;
```
[the remark this answers is not in the document]
Comment (SkyToGround) [reply src/Source.cpp]: I never did get around to writing unit tests for _Source.cpp_ thus I did not catch this. I have removed the useless code.

File: src/StreamMaster.h [hunk 6]
```diff
@@ -137,7 +137,7 @@ template <typename Streamer> class StreamMaster {
   /// stream is in any error state
   const StreamMasterError status() {
     for (auto &s : Streamers) {
-      if (s.second.runStatus().connectionOK()) {
+      if (s.second.runStatus() >= StreamerError::IS_CONNECTED) {
```
[the remark this answers is not in the document]
Comment (SkyToGround) [reply src/StreamMaster.h]: This is one of the things I forgot to fix yesterday. I changed the name of the original type from `StreamerError` into `StreamerStatus` but forgot to change a `using` statement. I have since fixed that.

File: src/Streamer.cpp [hunk 7]
```diff
@@ -22,19 +22,18 @@ FileWriter::Streamer::Streamer(const std::string &Broker,
...
-FileWriter::Streamer::connect(std::string TopicName) {
-
-  LOG(Sev::Debug, "Connecting to {}", TopicName);
+std::pair<FileWriter::Status::StreamerStatus, FileWriter::ConsumerPtr>
+FileWriter::createConsumer(std::string const TopicName,
+                           FileWriter::StreamerOptions const Options) {
+  LOG(Sev::Debug, "Connecting to \"{}\"", TopicName);
   try {
-    Consumer.reset(new KafkaW::Consumer(Options.Settings));
+    FileWriter::ConsumerPtr Consumer(new KafkaW::Consumer(Options.Settings));
```
[the remark this answers is not in the document]
Comment (SkyToGround) [reply src/Streamer.cpp]: Yes! Done!

File: src/FlatbufferMessage.h [hunk 8]
```diff
@@ -0,0 +1,48 @@
...
+#include <cstdint>
+#include <librdkafka/rdkafka.h>
+#include <librdkafka/rdkafkacpp.h>
+#include <memory>
+#include <vector>
+
+namespace FileWriter {
+class BufferTooSmallError : public std::runtime_error {
+public:
+  BufferTooSmallError(const std::string &what) : std::runtime_error(what){};
```
[the remark this answers is not in the document]
Comment (SkyToGround) [reply src/FlatbufferMessage.h]: Right!

File: src/FlatbufferMessage.cpp (hunk 2 above)
Comment (SkyToGround) [reply src/FlatbufferMessage.cpp]: True, but it does not hur either. Seeing as you mentioned it, there is some other `const` weirdness on that same line. I have now fixed that.

File: src/FlatbufferReader.cpp (hunk 3 above)
Comment (SkyToGround) [reply src/FlatbufferReader.cpp]: Yes, fixed.

File: src/Streamer.cpp (hunk 4 above)
Comment (SkyToGround) [reply src/Streamer.cpp]: The timing code is an excellent candidate for removing from the `Streamer` class and put somewhere else in order to simplify unit testing and modularise the code a bit. Until then, I have done as you suggested.

File: src/StreamMaster.h (hunk 6 above)
[the remark this answers is not in the document]
Comment (SkyToGround) [reply src/StreamMaster.h]: Oh, looks like I have to fix that for `StreamMaster` as well.

File: src/CMakeLists.txt [hunk 9]
```diff
@@ -167,6 +168,7 @@ add_library(${tgt} OBJECT
   ${kafka_to_nexus_SRC}
   ${kafka_to_nexus_INC}
 )
+set_property(TARGET ${tgt} PROPERTY CXX_STANDARD 14)
```
[the remark this answers is not in the document]
Comment (SkyToGround) [reply src/CMakeLists.txt]: I do not disagree with you so lets do that.

File: src/FlatbufferMessage.cpp (hunk 1 above)
Comment (SkyToGround) [reply src/FlatbufferMessage.cpp]: Done!

File: src/Errors.cpp [hunk 10]
```diff
@@ -60,58 +60,24 @@ StreamMasterError StreamMasterError::STREAMMASTER_ERROR() {
...
-  switch (Error.Value) {
-  case 1:
+const std::string FileWriter::Status::Err2Str(const StreamerStatus &Error) {
+  switch (Error) {
+  case StreamerStatus::OK:
+    return "No error.";
+  case StreamerStatus::WRITING:
     return "Writing";
-  case 0:
+  case StreamerStatus::HAS_FINISHED:
```
[the remark this answers is not in the document]
Comment (SkyToGround) [reply src/Errors.cpp]: Yes, now lets see if we can fix the other 511 locations in the code where `enum class` should be used but is not.

[the remark this answers is not in the document]
Comment (mattclarke) [reply src/Errors.cpp]: Different PR please! ;)

**Comment by SkyToGround** [comment]
This branch has passed all the integration tests that I intended to do (see description of pull request). I will fix the conflict with the master branch and then I will consider this branch ready to be merged.

**Comment by SkyToGround** [comment]
Merged with master and ran automatic integration tests without problem.

File: src/FlatbufferMessage.h [hunk 11]
```diff
@@ -0,0 +1,51 @@
...
+
+class NotValidFlatbuffer : public std::runtime_error {
+public:
+  explicit NotValidFlatbuffer(const std::string &what)
+      : std::runtime_error(what){};
+};
+/// \todo Profile code to determine if the exceptions are a performance problem
+class FlatbufferMessage {
+public:
+  FlatbufferMessage();
```
Comment (SkyToGround) [inline src/FlatbufferMessage.h]: Documentation for this class.

File: src/FlatbufferMessage.h [hunk 12]
```diff
@@ -0,0 +1,51 @@
...
+  explicit UnknownFlatbufferID(const std::string &what)
+      : std::runtime_error(what){};
+};
+
+class NotValidFlatbuffer : public std::runtime_error {
+public:
+  explicit NotValidFlatbuffer(const std::string &what)
+      : std::runtime_error(what){};
+};
+/// \todo Profile code to determine if the exceptions are a performance problem
```
Comment (SkyToGround) [inline src/FlatbufferMessage.h]: Create ticket for todo comment.

File: src/FlatbufferMessage.h [hunk 13]
```diff
@@ -0,0 +1,51 @@
...
+class FlatbufferMessage {
+public:
+  FlatbufferMessage();
+  FlatbufferMessage(char const *Pointer, size_t const Size);
```
Comment (SkyToGround) [inline src/FlatbufferMessage.h]: Come up with better name (suggestion: MessageDataPtr).

File: src/FlatbufferMessage.cpp [hunk 14]
```diff
@@ -0,0 +1,38 @@
+#include "FlatbufferMessage.h"
+#include "FlatbufferReader.h"
+
+namespace FileWriter {
+FlatbufferMessage::FlatbufferMessage() : Valid(false) {}
```
Comment (SkyToGround) [inline src/FlatbufferMessage.cpp]: Remove if not being used.

Comment (SkyToGround) [reply src/FlatbufferMessage.cpp]: Or put in header.

File: src/FlatbufferMessage.cpp [hunk 15]
```diff
@@ -0,0 +1,38 @@
...
+
+FlatbufferMessage::FlatbufferMessage(char const *const Pointer,
+                                     size_t const Size)
```
Comment (SkyToGround) [inline src/FlatbufferMessage.cpp]: Set valid to false.

File: src/tests/MessageTest.cpp [hunk 16]
```diff
@@ -0,0 +1,81 @@
...
+  std::unique_ptr<char[]> TestData(new char[8]);
+  std::memcpy(TestData.get() + 4, TestKey.c_str(), 4);
+  auto CurrentMessage = FlatbufferMessage(TestData.get(), 8);
+  EXPECT_TRUE(CurrentMessage.isValid());
+  EXPECT_EQ(CurrentMessage.getTimestamp(), std::uint64_t(42));
+  EXPECT_EQ(CurrentMessage.getSourceName(), "SomeSourceName");
+  EXPECT_EQ(CurrentMessage.size(), size_t(8));
+}
+
+TEST_F(MessageClassTest, WrongKey) {
```
Comment (SkyToGround) [inline src/tests/MessageTest.cpp]: Change to flatbuffer id, not "Key".

File: src/Streamer.cpp [hunk 17]
```diff
@@ -43,102 +53,129 @@ FileWriter::Streamer::connect(std::string TopicName) {
...
+  // Convert from KafkaW to FlatbufferMessage, handles validation of flatbuffer
+  auto KafkaMessage = Poll.isMsg();
+  std::unique_ptr<FlatbufferMessage> Message;
+  try {
+    Message.reset(new FlatbufferMessage(
+        reinterpret_cast<const char *>(KafkaMessage->data()),
+        KafkaMessage->size()));
+  } catch (std::runtime_error &Error) {
+    LOG(Sev::Warning,
+        "Message that is not a valid flatbuffer encountered. The error was: {}",
```
Comment (SkyToGround) [inline src/Streamer.cpp]: Log message offset, i.e. add code for passing around the offset.

File: src/Streamer.cpp [hunk 18]
```diff
@@ -43,102 +53,129 @@ FileWriter::Streamer::connect(std::string TopicName) {
...
+        Error.what());
+    return ProcessMessageResult::ERR;
   }
 
-  // Make sure that the message source is relevant and that the message is in
-  // the correct time window
-  DemuxTopic::DT MessageTime =
-      MessageProcessor.time_difference_from_message(Message);
-  if (std::find(Sources.begin(), Sources.end(), MessageTime.sourcename) ==
+  LastMessageTimestamp = systemTime(); // For dealing with messsage timeouts
```
Comment (SkyToGround) [inline src/Streamer.cpp]: Add todo and JIRA issue about possible performance penalties of checking the system time.

File: src/DemuxTopic.cpp [hunk 19]
```diff
@@ -6,102 +6,38 @@
...
 DemuxTopic::~DemuxTopic() { LOG(Sev::Debug, "dtor"); }
 
 DemuxTopic::DemuxTopic(DemuxTopic &&x) { swap(*this, x); }
 
 void swap(DemuxTopic &x, DemuxTopic &y) {
   using std::swap;
-  swap(x._topic, y._topic);
-  swap(x._sources_map, y._sources_map);
-  swap(x._stop_time, y._stop_time);
+  swap(x.Topic, y.Topic);
```
Comment (SkyToGround) [inline src/DemuxTopic.cpp]: Remove "using std::swap".

File: src/KafkaW/Consumer.cpp [hunk 20]
```diff
@@ -251,9 +251,8 @@ PollStatus Consumer::poll() {
   }
 
   static_assert(sizeof(char) == 1, "Failed: sizeof(char) == 1");
-  std::unique_ptr<Msg> m2(new Msg);
-
-  m2->MsgPtr = msg;
+  std::unique_ptr<Msg> m2(new Msg((std::uint8_t *)msg->payload, msg->len,
```
Comment (SkyToGround) [inline src/KafkaW/Consumer.cpp]: Make into make_unique.

File: src/Errors.h [hunk 21]
```diff
@@ -74,43 +74,15 @@ class StreamMasterError {
...
-  ///
-  /// @param[in]  Other  The other
-  ///
-  /// @return     True if the status is the same, False otherwise.
-  ///
-  bool operator==(const StreamerError &Other) { return Value == Other.Value; }
-
-private:
-  int Value{-1000};
+enum class StreamerStatus {
```
Comment (SkyToGround) [inline src/Errors.h]: Fix docstrings in the whole file.

File: src/KafkaW/Consumer.h [hunk 22]
```diff
@@ -9,21 +9,32 @@
 
 namespace KafkaW {
 
-class Inspect;
+class ConsumerBase {
```
Comment (SkyToGround) [inline src/KafkaW/Consumer.h]: Rename to ConsumerInterface.

File: src/FlatbufferMessage.h (hunk 11 above)
Comment (SkyToGround) [reply src/FlatbufferMessage.h]: Done.

File: src/FlatbufferMessage.h (hunk 12 above)
Comment (SkyToGround) [reply src/FlatbufferMessage.h]: Done.

File: src/FlatbufferMessage.h (hunk 11 above)
Comment (SkyToGround) [reply src/FlatbufferMessage.h]: Done.

File: src/FlatbufferMessage.h (hunk 13 above)
Comment (SkyToGround) [reply src/FlatbufferMessage.h]: Done.

File: src/KafkaW/Consumer.cpp (hunk 20 above)
Comment (SkyToGround) [reply src/KafkaW/Consumer.cpp]: Done.

File: src/KafkaW/Consumer.h (hunk 22 above)
Comment (SkyToGround) [reply src/KafkaW/Consumer.h]: Done.

File: src/FlatbufferMessage.cpp (hunk 14 above)
Comment (SkyToGround) [reply src/FlatbufferMessage.cpp]: It is being used and done.

File: src/FlatbufferMessage.cpp (hunk 15 above)
Comment (SkyToGround) [reply src/FlatbufferMessage.cpp]: Done.

File: src/tests/MessageTest.cpp (hunk 16 above)
Comment (SkyToGround) [reply src/tests/MessageTest.cpp]: Done.

File: src/Errors.h (hunk 21 above)
Comment (SkyToGround) [reply src/Errors.h]: Done.

File: src/Streamer.cpp (hunk 17 above)
Comment (SkyToGround) [reply src/Streamer.cpp]: Done.

**Comment by SkyToGround** [comment]
I have now fixed all comments and merged the master branch into this branch. @matthew-d-jones and @mattclarke , please take another look at this at your earliest convenience.

File: src/DemuxTopic.cpp [hunk 23]
```diff
@@ -6,105 +6,38 @@
...
-
-DemuxTopic::DT DemuxTopic::time_difference_from_message(Msg const &msg) {
-  auto &reader = FlatbufferReaderRegistry::find(msg);
-  if (!reader) {
-    LOG(Sev::Error, "ERROR unknown schema id?");
-    return DT::ERR();
-  }
-  auto srcn = reader->source_name(msg);
-  return DT(srcn, reader->timestamp(msg));
+  swap(x.Topic, y.Topic);
```
Comment (mattclarke) [inline src/DemuxTopic.cpp]: I thought we were going to fully qualify this and lose the using.

Comment (SkyToGround) [reply src/DemuxTopic.cpp]: Sorry, forgot about that one. This is now fixed.

File: src/DemuxTopic.cpp [hunk 24]
```diff
@@ -6,105 +6,37 @@
...
-
-ProcessMessageResult ProcessMessageResult::STOP() {
-  ProcessMessageResult ret;
-  ret._ts = -3;
-  return ret;
-}
-
-DemuxTopic::DemuxTopic(std::string topic)
-    : _topic(topic), _stop_time(std::numeric_limits<uint64_t>::max()) {}
+DemuxTopic::DemuxTopic(std::string TopicName) : Topic(TopicName) {}
```
[the remark this answers is not in the document]
Comment (matthew-d-jones) [reply src/DemuxTopic.cpp]: I generally think it is neater to put single line constructors+destructors in the header. I didn't find any advice in LLVM guidelines about it though.

File: src/FlatbufferMessage.h [hunk 25]
```diff
@@ -0,0 +1,86 @@
...
+  /// \param[in] BufferPtr Pointer to memory location containing flatbuffer.
+  /// \param[in] Size Size of flatbuffer in bytes.
+  /// \throws FileWriter::BufferTooSmallError If the size argument is < 8, it
+  /// can not be a flatbuffer as the identifier is stored in bytes 4 to 8.
+  /// \throws FileWriter::UnknownFlatbufferID If the flatbuffer ID (bytes 4 to
+  /// 8) is not found in the database, this exception is thrown.
+  /// \throws FileWriter::NotValidFlatbuffer The constructor runs
+  /// FileWriter::FlatbufferReader::verify() on the flatbuffer and this
+  /// exception is thrown if it returns false.
+  FlatbufferMessage(char const *BufferPtr, size_t const Size);
```
Comment (matthew-d-jones) [inline src/FlatbufferMessage.h]: The `const` for `Size`has no effect here in the function declaration.

File: src/KafkaW/Consumer.h [hunk 26]
```diff
@@ -9,21 +9,32 @@
 
 namespace KafkaW {
 
-class Inspect;
+class ConsumerInterface {
+public:
+  ConsumerInterface() = default;
+  virtual ~ConsumerInterface() = default;
+  virtual void addTopic(std::string Topic,
```
Comment (matthew-d-jones) [inline src/KafkaW/Consumer.h]: virtual methods can't have default arguments

File: src/KafkaW/Consumer.h [hunk 27]
```diff
@@ -9,21 +9,32 @@
...
+};
 
-class Consumer {
+class Consumer : public ConsumerInterface {
 public:
   Consumer(BrokerSettings opt);
   Consumer(Consumer &&) = delete;
   Consumer(Consumer const &) = delete;
-  ~Consumer();
+  virtual ~Consumer();
```
Comment (matthew-d-jones) [inline src/KafkaW/Consumer.h]: Using `override` is preferred instead of `virtual`.

File: src/KafkaW/Msg.h [hunk 28]
```diff
@@ -2,20 +2,31 @@
...
 namespace KafkaW {
 // Want to expose this typedef also for users of this namespace
 using uchar = unsigned char;
 
 class Msg {
 public:
+  Msg() = default;
+  Msg(std::uint8_t const *Pointer, size_t Size,
+      std::function<void()> DataDeleter)
+      : DataPointer(Pointer), DataSize(Size), OnDelete(DataDeleter) {}
```
Comment (matthew-d-jones) [inline src/KafkaW/Msg.h]: May as well avoid the copy here: `OnDelete(std::move(DataDeleter))`

File: src/KafkaW/Msg.h [hunk 29]
```diff
@@ -2,20 +2,31 @@
...
+  Msg(std::uint8_t const *Pointer, size_t Size,
+      std::function<void()> DataDeleter, std::int64_t Offset)
+      : DataPointer(Pointer), DataSize(Size), OnDelete(DataDeleter),
```
Comment (matthew-d-jones) [inline src/KafkaW/Msg.h]: As above

File: src/KafkaW/Msg.h [hunk 30]
```diff
@@ -2,20 +2,31 @@
...
+        MessageOffset(Offset) {}
```
Comment (matthew-d-jones) [inline src/KafkaW/Msg.h]: There is an implicit cast of `Offset` from signed to unsigned here, best to make explicit with `static_cast` if intentional.

File: src/KafkaW/PollStatus.cpp [hunk 31]
```diff
@@ -25,28 +25,25 @@ PollStatus PollStatus::Empty() {
 PollStatus PollStatus::newWithMsg(std::unique_ptr<Msg> Msg) {
   PollStatus ret;
   ret.state = PollStatusContent::Msg;
-  ret.data = Msg.release();
+  ret.StoredMessage = std::move(Msg);
   return ret;
 }
 
 PollStatus::PollStatus(PollStatus &&x)
```
Comment (matthew-d-jones) [inline src/KafkaW/PollStatus.cpp]: Should be marked `noexcept`

File: src/Streamer.cpp [hunk 32]
```diff
@@ -8,6 +8,16 @@ std::chrono::milliseconds systemTime() {
...
 }
+bool stopTimeElapsed(std::uint64_t MessageTimestamp,
+                     std::chrono::milliseconds Stoptime) {
+  if (Stoptime.count() > 0 and
+      static_cast<std::int64_t>(MessageTimestamp) >
+          std::chrono::duration_cast<std::chrono::nanoseconds>(Stoptime)
+              .count()) {
+    return true;
+  }
+  return false;
```
Comment (matthew-d-jones) [inline src/Streamer.cpp]: The if statement is superfluous, could just
```
return Stoptime.count() > 0 and
    static_cast<std::int64_t>(MessageTimestamp) >
        std::chrono::duration_cast<std::chrono::nanoseconds>(Stoptime)
            .count();
```

File: src/Streamer.cpp [hunk 33]
```diff
@@ -48,102 +58,129 @@ FileWriter::Streamer::connect(std::string TopicName) {
...
     }
+    return {FileWriter::Status::StreamerStatus::WRITING, std::move(Consumer)};
   } catch (std::exception &Error) {
     LOG(Sev::Error, "{}", Error.what());
-    return StreamerError::CONFIGURATION_ERROR();
+    return {FileWriter::Status::StreamerStatus::CONFIGURATION_ERROR, nullptr};
   }
 
-  return StreamerError::WRITING();
+  return {FileWriter::Status::StreamerStatus::UNKNOWN_ERROR, nullptr};
```
Comment (matthew-d-jones) [inline src/Streamer.cpp]: All exceptions are caught on line 67, so this line is unreachable anyway.

File: src/Streamer.cpp [hunk 34]
```diff
@@ -48,102 +58,129 @@ FileWriter::Streamer::connect(std::string TopicName) {
...
 
-  // convert from KafkaW to Msg
-  Msg Message(Msg::fromKafkaW(Poll.isMsg()));
-  if (Message.type == MsgType::Invalid) {
-    return ProcessMessageResult::ERR();
+  // Convert from KafkaW to FlatbufferMessage, handles validation of flatbuffer
+  auto KafkaMessage = Poll.isMsg();
+  std::unique_ptr<FlatbufferMessage> Message;
+  try {
+    Message.reset(new FlatbufferMessage(
```
Comment (matthew-d-jones) [inline src/Streamer.cpp]: I didn't really understand what you said in the code review at this point, declaring `Message` outside the `try` statement doesn't, and shouldn't, stop you from using `make_unique` here.

File: src/Streamer.cpp [hunk 35]
```diff
@@ -48,102 +58,129 @@ FileWriter::Streamer::connect(std::string TopicName) {
...
-  MessageInfo.message(Message.size());
+  MessageInfo.newMessage(Message->size());
 
   // Write the message. Log any error and return the result of processing
   ProcessMessageResult result =
-      MessageProcessor.process_message(std::move(Message));
-  LOG(Sev::Debug, "Processed: {}::{}\tpulse_time: {}", MessageProcessor.topic(),
-      MessageTime.sourcename, result.ts());
-  if (!result.is_OK()) {
+      MessageProcessor.process_message(*Message.get());
```
Comment (matthew-d-jones) [inline src/Streamer.cpp]: `.get()` is redundant here.

File: src/tests/DemuxerTests.cpp [hunk 36]
```diff
@@ -0,0 +1,174 @@
...
+  FileWriter::FlatbufferMessage CurrentMessage(TestData, 8);
+  ProcessMessageResult Result;
+  DemuxTopic TestDemuxer("SomeTopicName");
+  DummyWriter::ptr Writer(new DummyWriter);
+  Source DummySource(SourceName, TestKey, std::move(Writer));
+  TestDemuxer.add_source(std::move(DummySource));
+  ASSERT_EQ(TestDemuxer.sources().size(), size_t(1));
+  EXPECT_NO_THROW(TestDemuxer.sources().at(SourceName));
+  EXPECT_NO_THROW(Result =
+                      TestDemuxer.process_message(std::move(CurrentMessage)));
```
Comment (matthew-d-jones) [inline src/tests/DemuxerTests.cpp]: Shouldn't use `std::move` here, the parameter is used as `const &` so it will have no effect.

Comment (matthew-d-jones) [reply src/tests/DemuxerTests.cpp]: (repeated in a few tests)

File: src/tests/FastSampleEnvironmentWriterTests.cpp [hunk 37]
```diff
@@ -35,6 +37,12 @@ class FastSampleEnvironmentReader : public ::testing::Test {
   void SetUp() override {
     ASSERT_NE(RawBuffer.get(), nullptr);
     ReaderUnderTest.reset(new senv::SampleEnvironmentDataGuard());
```
Comment (matthew-d-jones) [inline src/tests/FastSampleEnvironmentWriterTests.cpp]: `make_unique` can also be used here

File: src/DemuxTopic.cpp (hunk 24 above)
[the remark this answers is not in the document]
Comment (SkyToGround) [reply src/DemuxTopic.cpp]: Done.

File: src/FlatbufferMessage.h (hunk 25 above)
Comment (SkyToGround) [reply src/FlatbufferMessage.h]: That is one of the most esoteric rules in C++ that I have encountered. Do you have a reference to why this is so? Regardless, the rule is way too esoteric for me to change the code.

File: src/KafkaW/Consumer.h (hunk 26 above)
Comment (SkyToGround) [reply src/KafkaW/Consumer.h]: Turns out that they can but they do not do anything in this case. I have removed the default argument.

File: src/KafkaW/Consumer.h (hunk 27 above)
Comment (SkyToGround) [reply src/KafkaW/Consumer.h]: This one was slightly weird to me seeing as the destructor is not really overridden in the same way other member functions are. I have changed the code.

File: src/KafkaW/Msg.h (hunk 28 above)
Comment (SkyToGround) [reply src/KafkaW/Msg.h]: Right.

File: src/KafkaW/Msg.h (hunk 29 above)
Comment (SkyToGround) [reply src/KafkaW/Msg.h]: Done.

File: src/KafkaW/Msg.h (hunk 30 above)
Comment (SkyToGround) [reply src/KafkaW/Msg.h]: My mistake. Was supposed to use `std::int64_t` as the member variable. This has now been fixed.

File: src/KafkaW/PollStatus.cpp (hunk 31 above)
Comment (SkyToGround) [reply src/KafkaW/PollStatus.cpp]: Done.

File: src/Streamer.cpp (hunk 32 above)
Comment (SkyToGround) [reply src/Streamer.cpp]: Correct, fixed.

File: src/Streamer.cpp (hunk 33 above)
Comment (SkyToGround) [reply src/Streamer.cpp]: I consider it good coding practice to always have a return statement on the last line of a function in  case something changes in the future. Furthermore, exceptions does not have to inherit from `std::exception`.

File: src/Streamer.cpp (hunk 34 above)
Comment (SkyToGround) [reply src/Streamer.cpp]: I do not remember what I said but I remember what I meant: I can not put the declaration in the try statement as I need the Message after the try statement as well. I have changed to using `std::make_unique<>()` though.

File: src/Streamer.cpp (hunk 35 above)
Comment (SkyToGround) [reply src/Streamer.cpp]: Fixed.

File: src/tests/DemuxerTests.cpp (hunk 36 above)
Comment (SkyToGround) [reply src/tests/DemuxerTests.cpp]: Done.

File: src/tests/FastSampleEnvironmentWriterTests.cpp (hunk 37 above)
Comment (SkyToGround) [reply src/tests/FastSampleEnvironmentWriterTests.cpp]: Right.

**Comment by matthew-d-jones** [comment]
How does `std::unique_ptr<HDFWriterModule> HDFWriterModule;` not cause a problem with clang? :/

**Comment by SkyToGround** [comment]
@matthew-d-jones I guess that technically it is possible to figure out that one of them is a type and the other one is not.

**Comment by SkyToGround** [comment]
Bloody finally.

File: src/FlatbufferMessage.h (hunk 25 above)
Comment (matthew-d-jones) [reply src/FlatbufferMessage.h]: In this case the `const`ness is an implementation detail which is irrelevant to the interface, on the other hand if that seems odd to people then that is reason enough to leave `const` in the declaration.

Comment (SkyToGround) [reply src/FlatbufferMessage.h]: I understand that this is the reason why `const` is not required. What makes this surprising to me is because having the interface reflect the implementation requires only one rule in the C++ standard whereas the actual behaviour requires two rules in the standard.

Anyway, I am willing to change the code if you can find one more person that agrees with you.
