### PR TITLE
Fix long integer bug

### LINKED ISSUE #133: Long integers cause error
For example:
```json
{
    "name": "features",
    "values": 10138143369737381149,
    "type": "dataset",
    "dataset": {
        "type": "uint64"
    }
}
```

### PR DESCRIPTION
**Pull request by matthew-d-jones**
Fixes #133 

Fixes a bug with getting long integers from the json command. This stopped `features` datasets being written for the example ESS NeXus files.

Added test for writing each of the four integer types.

### CODE REVIEW

File: src/tests/HDFFile.cxx [hunk 1]
```diff
@@ -1265,3 +1255,43 @@ TEST_F(T_CommandHandler, data_f142) { T_CommandHandler::data_f142(); }
 TEST_F(T_CommandHandler, dataset_static_1d_string_variable) {
   T_CommandHandler::dataset_static_1d_string_variable();
 }
+
+template <typename T>
+void testType(FileWriter::HDFFile &TestFile,
```
Comment (dominikwerder) [inline src/tests/HDFFile.cxx]: Would a function name like `verifyWrittenDatatype` be more appropriate? Because, all datatypes are are written to the same HDF file in the same test run.
