### PR TITLE
Catch exception from writer module init

### LINKED ISSUE #253: Catch exception during initialization of a writer module
Runtime errors during the initialization of a writer module should be catched.

### PR DESCRIPTION
**Pull request by dominikwerder**
### Description of work

- Catch exceptions from writer module initialization
- Add more details via `throw_with_nested` in some places
- Attempt HDF5 `flush` and `close` only given a valid file handle to avoid the corresponding exceptions in that case
- Factored body of loop into new function `extractStreamInformationFromJsonForSource`

### Issue

Closes #253 

### Acceptance Criteria

- Wrong settings especially in the `stream` children of `nexus_structure` should now be caught

### CODE REVIEW

File: src/HDFFile.cpp [hunk 1]
```diff
@@ -853,11 +853,15 @@ void HDFFile::init(nlohmann::json const &nexus_structure,
...
-    h5file.close();
-    LOG(Sev::Debug, "closed");
+    if (h5file.is_valid()) {
+      LOG(Sev::Debug, "flushing");
+      flush();
+      LOG(Sev::Debug, "closing");
+      h5file.close();
+      LOG(Sev::Debug, "closed");
+    } else {
+      LOG(Sev::Debug, "File is not valid, skip close.");
```
Comment (matthew-d-jones) [inline src/HDFFile.cpp]: Sounds worthy of `Sev::Error` to me.
