### PR TITLE
Fix hdf objects cleanup

### LINKED ISSUE #47: Some HDF handles are left open
Some HDF handles are left open after the file writer is finished with writing the file. This prevents the file from being properly closed as one can notice when one tries to use that same file again.

### PR DESCRIPTION
**Pull request by dominikwerder**
Closes #47.

### CODE REVIEW

File: src/tests/HDFFile.cxx [hunk 1]
```diff
@@ -478,6 +478,14 @@ class T_CommandHandler : public testing::Test {
...
 
     H5Fclose(fid);
+
+    {
+      // now try to recreate the file for testing:
+      auto x =
+          H5Fcreate("tmp-ev42.h5", H5F_ACC_TRUNC, H5P_DEFAULT, H5P_DEFAULT);
+      ASSERT_GE(x, 0);
+      H5Fclose(x);
+    }
```
Comment (matthew-d-jones) [inline src/tests/HDFFile.cxx]: If you've given it its own scope and a title, why not make it a method? `data_ev42()` is already far too large and difficult to follow.
```
void recreate_file_for_testing() {
  auto x =
    H5Fcreate("tmp-ev42.h5", H5F_ACC_TRUNC, H5P_DEFAULT, H5P_DEFAULT);
  ASSERT_GE(x, 0);
  H5Fclose(x);
}
```

**Comment by dominikwerder** [comment]
Hi Matthew, I've just pushed my changes.

File: src/HDFFile.cxx [hunk 2]
```diff
@@ -141,141 +279,21 @@ int HDFFile::init(std::string filename,
...
-      SE(string name, Value const *jsv, hid_t nxparent)
-          : name(name), jsv(jsv), nxparent(nxparent), nxv(-1),
-            itr(jsv->MemberEnd()), basics(false) {
-        if (jsv->IsObject()) {
-          itr = jsv->MemberBegin();
-        }
-      }
-    };
-    std::deque<SE> stack;
     stack.push_back(SE{"/", &nexus_structure, -1});
```
Comment (matthew-d-jones) [inline src/HDFFile.cxx]: Use `emplace_back` instead of `push_back`: `stack.emplace_back("/", &nexus_structure, -1);`

File: src/HDFFile.cxx [hunk 3]
```diff
@@ -141,141 +279,21 @@ int HDFFile::init(std::string filename,
...
-          }
-          ++se.itr;
-        }
-      }
+  }
 
-      if (!have_child) {
-        stack.pop_back();
-      }
+  while (stack.size() > 0) {
```
Comment (matthew-d-jones) [inline src/HDFFile.cxx]: Use the `empty` method to test emptiness, rather than comparing size with 0: `while (!stack.empty()) {`

File: src/HDFFile.cxx [hunk 4]
```diff
@@ -338,8 +356,9 @@ uint64_t FBSchemaReader::teamid_impl(Msg &msg) { return 0; }
 FBSchemaWriter::FBSchemaWriter() {}
```
Comment (matthew-d-jones) [inline src/HDFFile.cxx]: Use `= default`

File: src/HDFFile.cxx [hunk 5]
```diff
@@ -115,6 +115,144 @@ static void write_attribute(hid_t loc, std::string name, T value) {
...
+  string name;
+  rapidjson::Value const *jsv;
+  hid_t nxparent;
+  hid_t nxv;
+  hid_t gid;
+  rapidjson::Value::ConstMemberIterator itr;
+  bool basics;
+  string nx_type{"group"};
+  SE(string name, rapidjson::Value const *jsv, hid_t nxparent)
+      : name(name), jsv(jsv), nxparent(nxparent), nxv(-1), gid(-1),
```
[the remark this answers is not in the document]
Comment (dominikwerder) [reply src/HDFFile.cxx]: OK, it's not a bottleneck at all though.

**Comment by dominikwerder** [comment]
Updated.
