### PR TITLE
310 exception throwing

### LINKED ISSUE #310: Throw exception in FlatbufferReader if key not found.
FlatbufferReader::ptr &find(std::string const &FlatbufferID) should throw an exception if _key_ not found

https://github.com/ess-dmsc/kafka-to-nexus/blob/9cf7b41ebeacec0b2ac1dbb55aecce9b4c307797/src/FlatbufferReader.h#L38-L39

### LINKED ISSUE #313: Implement exceptions in HDFWriterModule.h
Throw exception in HDFWriterModuleRegistry::find(std::string const &key) if key not found.

https://github.com/ess-dmsc/kafka-to-nexus/blob/9cf7b41ebeacec0b2ac1dbb55aecce9b4c307797/src/HDFWriterModule.h#L223-L224

### PR DESCRIPTION
**Pull request by mchorazak**
### Description of work

Both
`FlatbufferReaderRegistry::find(std::string const &FlatbufferID)` 
and 
`HDFWriterModuleRegistry::find(std::string const &key)` 
now use `std::map::at` to look for map entries. `std::map::at` throws `std::out_of_range` if there is no value corresponding to a given key. This is handled appropriately whenever `find` is called.

Closes #310 
Closes #313 

### Acceptance Criteria
`FlatbufferReaderRegistry::find(std::string const &FlatbufferID)`
`HDFWriterModuleRegistry::find(std::string const &key)`

### Unit Tests
Adjusted `(WriterRegistrationTest, StrKeyNotFound)` to expect `out_of_range` errors.

---

## Code Review (To be filled in by the reviewer only)

- [ ] Is the code of an acceptable quality?
- [ ] Do the changes function as described and is it robust?

---

## Nominate for Group Code Review (Anyone can nominate it)
Indicate if you think the code should be reviewed in a Thursday code review session.

- [ ] Recommend for group code review

Also, nominate it on the code_review Slack channel (does someone want to automate this?).

### CODE REVIEW

File: src/HDFWriterModule.cpp [hunk 1]
```diff
@@ -12,11 +12,8 @@ std::map<std::string, HDFWriterModuleRegistry::ModuleFactory> &getFactories() {
 HDFWriterModuleRegistry::ModuleFactory &find(std::string const &key) {
   static HDFWriterModuleRegistry::ModuleFactory empty;
   auto &_items = getFactories();
-  auto f = _items.find(key);
-  if (f == _items.end()) {
-    return empty;
-  }
-  return f->second;
+  auto &f = _items.at(key);
+  return f;
```
Comment (mattclarke) [inline src/HDFWriterModule.cpp]: One line:
return _items.at(key);

File: src/HDFWriterModule.cpp [hunk 2]
```diff
@@ -12,11 +12,7 @@ std::map<std::string, HDFWriterModuleRegistry::ModuleFactory> &getFactories() {
 HDFWriterModuleRegistry::ModuleFactory &find(std::string const &key) {
   static HDFWriterModuleRegistry::ModuleFactory empty;
```
Comment (dominikwerder) [inline src/HDFWriterModule.cpp]:
```suggestion
```

If `find` now signals "not found' via an exception instead of the previous "empty value" then you can remove `empty` as well.
